feat: connector external event log - json
8xFF/atm0s-media-server pull request #132
Opened 2023-12-27 05:39 UTC by luongngocminh

Connector Server now accepts custom 
- http-port
- node-id
- message queue URI and channel which will provide support multiple protocol such as NATS, AMQP, MQTT, currently only Nats is supported
- serializer type: JSON and Protobuf, currently only JSON is Implemented

![image](https://github.com/8xFF/atm0s-media-server/assets/9526028/84571a4f-30f7-4d2f-be08-ff6c9459363f)

2023-12-27 07:30 UTC, giangndm commented
@luongngocminh I have concern about how developer handle received event, which don't have type.

2023-12-27 07:38 UTC, giangndm requested changes

2023-12-27 07:38 UTC, giangndm commented on servers/media-server/Cargo.toml
This should include inside connector feature

2023-12-27 07:38 UTC, giangndm commented on servers/media-server/src/server/connector/transports/nats.rs
> +            sub.unsubscribe().unwrap();
should not use unwrap here

2023-12-27 07:38 UTC, giangndm commented on servers/media-server/src/server/connector.rs
> +    let transporter: Result<Box<dyn Transporter>, String> = match protocol.next() {
Should move url parse to separated function for testable

2023-12-27 07:38 UTC, giangndm commented on servers/media-server/src/server/connector/transports/nats.rs
> +        let res = nats::connect(&uri);
Are you using SYNC version of NATS? It it better to switch to ASYNC version for better performance and avoiding blocking other part.

2023-12-27 15:40 UTC, giangndm commented on servers/media-server/Cargo.toml
> +serde_json = "1.0"
Do you use serde_json outside connector?

2023-12-27 15:40 UTC, giangndm commented on servers/media-server/Cargo.toml
> +serde_json = "1.0"
Do you use serde_json outside connector?

2024-01-01 16:38 UTC, giangndm requested changes

2024-01-01 16:38 UTC, giangndm commented on packages/cluster/Cargo.toml
> +prost = "0.12"
prost seam to unused in cluster crate

2024-01-01 16:38 UTC, giangndm commented on packages/cluster/src/define/rpc/connector.rs
> +// use atm0s_sdn::NodeId;
If don't use, please delete rather than comment out

2024-01-01 16:38 UTC, giangndm commented on packages/cluster/src/define/endpoint.rs
> +    MediaEndpointLog(MediaEndpointLogEvent),
Log event or request? For handling acknowledgement, it should be request

2024-01-01 16:38 UTC, giangndm commented on packages/protocol/Cargo.toml
> +
need more info for publishing to crates.io

2024-01-01 16:38 UTC, giangndm commented on packages/protocol/src/media_endpoint_log.proto
> +  uint32 precision = 2;
precision should be u8 or using fixed precision 2

2024-01-01 16:38 UTC, giangndm commented on packages/protocol/src/media_endpoint_log.proto
> +message SendStreamEvent {
Refactor SendStreamEvent with sub messages type inside SendStreamEvent

2024-01-01 16:38 UTC, giangndm commented on servers/media-server/src/server/connector.rs
> +    http_port: u16,
We already has http_port in root server clap args

2024-01-01 16:38 UTC, giangndm commented on servers/media-server/src/server/connector.rs
> +    let api_service = OpenApiService::new(ConnectorHttpApis, "Connector Server", "1.0.0").server(format!("http://localhost:{}", http_port));
It should replace http url with "/"

2024-01-01 16:38 UTC, giangndm commented on servers/media-server/src/server/connector/serializers/json.rs
> +// pub struct JsonConnectorEventSerializer;
If not used, remove that

2024-01-01 16:38 UTC, giangndm commented on servers/media-server/src/server/connector/transports/mod.rs
> +    async fn send(&self, data: &[u8]) -> Result<(), String>;
We should not hard-coded that data transfer will be binary, instead we should parse Protocol object, then data serialize will be take care by protocol it-self.

2024-01-03 10:06 UTC, luongngocminh commented on servers/media-server/src/server/connector.rs
> +    let api_service = OpenApiService::new(ConnectorHttpApis, "Connector Server", "1.0.0").server(format!("http://localhost:{}", http_port));
what do you mean by this

2024-01-04 08:52 UTC, giangndm requested changes
Please fix errors

2024-01-05 09:14 UTC, giangndm approved these changes

2024-01-05 09:15 UTC, merged