fix: connector crashed when failed to connector to nats
8xFF/atm0s-media-server pull request #161
Opened 2024-01-09 04:08 UTC by luongngocminh

2024-01-09 04:16 UTC, giangndm commented
@luongngocminh I think it should handle error instead of ignore error. Current solution will lost package when NATS error.

The best solution is push event into queue (can be persistence on disk), only pop from queue if it successful sent to NATS, if NATS error it should reconnect and log error

2024-01-09 07:00 UTC, giangndm requested changes
We should implement mechanism for avoiding RPC handler being blocked, it simple put to a queue (persistence is the best, https://crates.io/crates/yaque), consume the queue the push to NATS, if it success consume the data.

2024-01-09 07:01 UTC, giangndm commented on servers/media-server/Cargo.toml
> +connector = ["nats", "prost", "queues"]
Or using https://crates.io/crates/yaque

2024-01-09 07:02 UTC, giangndm commented on servers/media-server/src/server/connector.rs
> +    if let Err(e) = transporter.connect().await {
It seam to auto re-connect on transport

2024-01-09 07:02 UTC, luongngocminh commented on servers/media-server/src/server/connector.rs
> +    if let Err(e) = transporter.connect().await {
It will try to reconnect when there are logs waiting to be send, this shouldn't crash the server

2024-01-15 06:47 UTC, giangndm commented
@luongngocminh Look good, please add some tests for ensure TransporterQueue working and fix some variable names. If the variable is used, shouldn't prefix it with "_"

2024-01-15 06:48 UTC, giangndm requested changes
@luongngocminh Look good, please add some tests for ensure TransporterQueue working and fix some variable names. If the variable is used, shouldn't prefix it with "_"

2024-01-15 18:46 UTC, giangndm requested changes

2024-01-15 18:46 UTC, giangndm commented on servers/media-server/src/server/connector/queue.rs
> +        sleep(Duration::from_millis(1001)).await;
Why we need sleep here?

2024-01-15 18:46 UTC, giangndm commented on servers/media-server/src/server/connector/queue.rs
> +        log::debug!("Polling Nats transporter");
in this context we don't know it is nats or whatever

2024-01-15 18:46 UTC, giangndm commented on servers/media-server/src/server/connector/queue.rs
> +        assert_eq!(message, received_message);
need to check queue is empty

2024-01-16 02:39 UTC, giangndm approved these changes

2024-01-16 02:40 UTC, merged