Feat/event hook
8xFF/atm0s-media-server pull request #420
Opened 2024-08-10 09:36 UTC by marverlous811

## Pull Request

### Description

Add a feature to send events to 3rd system through hook.

### Related Issue

[Issue 341](https://github.com/8xFF/atm0s-media-server/issues/341)

### Checklist

- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.
- [x] I have updated the documentation if necessary.
- [x] I have added appropriate tests, if applicable.

2024-08-11 08:47 UTC, jibon57 commented
@marverlous811 few comments:

- Do you think JW token or some kind of security by header will be better? So that end webhook receiver can verify the request? Simple hash mac with sha256/512 can be calculate with the body & send by header will be better or JW token.
-  Having an unique ID with each request will be helpful as well as. 
- Will system do retry in case HTTP attempt failed first time? In this case request need to go through a queue to make sure requests are sending in sequentially & not breaking it.

2024-08-11 14:08 UTC, marverlous811 commented
> @marverlous811 few comments:
> 
> * Do you think JW token or some kind of security by header will be better, so that end webhook receiver can verify the request? Simple hash mac with sha256/512 can be calculate with the body & send by header  or JW token.
> * Having an unique ID with each request will be helpful as well as.
> * Will system do retry in case HTTP attempt failed first time? In this case request need to go through a queue to make sure requests are sending in sequentially & not breaking it.

@jibon57:

- I think JWT is a good choice. Because it's the first version, I don't know how the third system calculates our hash. Maybe you can pass your system secret to the connector through the CLI param. I will use it as the key of JWT and the body as the payload, and you can decode and verify it in your system. Do you think that solution is good?
- I missed it. I will update the unique ID for each event tomorrow.
- The first version does not support the feature retry when a message fails. But in the future, we will update to ensure the message is sent successfully by a queue with ACK or maybe a dead-letter queue if need

2024-08-12 04:42 UTC, giangndm commented
@marverlous811 @jibon57 I think TLS + Endpoint is enough. For securing environment, we can add some token to endpoint and use TLS for avoiding man-in-middle attack.

2024-08-12 06:16 UTC, jibon57 commented
@giangndm  most of the time webhook endpoint always remain open/well known. Having a simple token in each request will be very easy to determine whether we need to process the request or not. You can simply calculate hash (md5,sha1 etc.) of the body using secret or add another option to set secret & use a header eg. HASH-SIGNATURE/HASH-TOKEN during sending any request. 

- I think `webhook-url` instated of `hook-uri` will be more appropriate name. 
- @marverlous811 I think retry is an important feature to be have for webhook. You may consider it for sooner.

2024-08-13 01:39 UTC, marverlous811 commented
@jibon57 I'll update the retry send hook soon, maybe this weekend. 

I use `hook-uri` because we support the webhook and other hook providers such as NATS or Kafka in the future. I use the protocol in URI to detect which node will used. Example: `nats://localhost:4222`. Default is webhook

2024-08-14 08:41 UTC, giangndm commented
@marverlous811 new rust version already has async trait, then we don't need async_trait anymore

2024-08-17 01:25 UTC, giangndm requested changes

2024-08-17 01:25 UTC, giangndm commented on docs/user-guide/features/third-party-system-hook.md
> +    event: 'session' | 'peer' | 'remote_track' | 'loacl_track',
have typo issue

2024-08-17 01:25 UTC, giangndm commented on packages/media_connector/src/hook_producer.rs
> +    pub async fn on_tick(&mut self) -> Option<()> {
We need to send more than one event per tick, the queue will full very soon

2024-08-20 06:41 UTC, marverlous811 commented
@giangndm, I have written new code that uses workers to send the hook. The Github action build job reported that our version of SQLX needs to be updated. Do you think we should update it now?

2024-08-21 02:28 UTC, giangndm commented
@marverlous811 sea-orm crate has some outdate dependence, may be we need to create an issue in sea-orm repo

2024-08-21 18:05 UTC, giangndm commented
@marverlous811 I just updated for fixing cargo-deny issue, please merge with latest source code

2024-08-25 18:29 UTC, giangndm commented
@marverlous811 I just refactored the PR. For simplicity, I used a direct struct generated from protobuf and converted it to binary or JSON based on the configuration parameter.

@jibon57 I agree that we should have some form of data protection. In the current implementation, to avoid making it more complicated, we can use a simple solution by implementing a hook endpoint that includes secure query or path parameters. With a HASH-SIGNATURE, we can place it into the headers, allowing us to implement it in the future without any BREAKING-CHANGES.

2024-08-26 11:25 UTC, jibon57 commented
@giangndm thanks. Yes, simple hash calculated by using body + secret and placed in header during sending post request to the webhook end point URL will be enough for the moment. This way the webhook end point can verify either it was coming from `atm0s-media-server` or not. Here we can use default secret or can have another option to set secret specifically for webhook.

2024-08-27 08:56 UTC, giangndm commented
@marverlous811 @jibon57 I merged it as a first version. Security or retry-backoff will be implemented soon

2024-08-27 08:56 UTC, merged